export const onRequestPost = async ({ request, env }: { request: Request; env: { RESEND_API_KEY: string } }) => {
    try {
        const data = await request.json() as any;
        const { name, email, service, message, fileLinks, details } = data;

        const isQuotation = service && (service.includes('Quotation') || service.includes('quotation'));

        if (!env.RESEND_API_KEY) {
            throw new Error('Missing RESEND_API_KEY in environment variables');
        }

        // Professional Email Styling
        const emailStyles = `font-family: sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eee; border-radius: 10px;`;
        const headerStyles = `background: #007bff; color: white; padding: 15px; border-radius: 8px 8px 0 0; text-align: center;`;

        const fileLinksHtml = fileLinks && fileLinks.length > 0
            ? `<div style="margin-top:20px;padding:15px;background:#f8f9fa;"><h3>📄 Uploaded Documents:</h3><ul>${fileLinks.map((link: string) => `<li><a href="${link}" style="color: #007bff;">Download File</a></li>`).join('')}</ul></div>`
            : '';

        const htmlBody = `
            <div style="${emailStyles}">
                <div style="${headerStyles}">
                    <h2 style="margin: 0;">${isQuotation ? '⚡ New Quotation Request' : '✉️ New Contact Inquiry'}</h2>
                </div>
                <div style="padding: 20px; background: #ffffff;">
                    <p>You have received a new ${isQuotation ? 'quotation request' : 'message'} from the website.</p>
                    
                    <table style="width: 100%; border-collapse: collapse;">
                        <tr>
                            <td style="padding: 10px 0; border-bottom: 1px solid #eee; font-weight: bold; width: 30%;">Name:</td>
                            <td style="padding: 10px 0; border-bottom: 1px solid #eee;">${name}</td>
                        </tr>
                        <tr>
                            <td style="padding: 10px 0; border-bottom: 1px solid #eee; font-weight: bold;">Email:</td>
                            <td style="padding: 10px 0; border-bottom: 1px solid #eee;"><a href="mailto:${email}" style="color: #007bff; text-decoration: none;">${email}</a></td>
                        </tr>
                        <tr>
                            <td style="padding: 10px 0; border-bottom: 1px solid #eee; font-weight: bold;">Service:</td>
                            <td style="padding: 10px 0; border-bottom: 1px solid #eee;">${service || 'General Inquiry'}</td>
                        </tr>
                        ${details ? `
                        <tr>
                            <td style="padding: 10px 0; border-bottom: 1px solid #eee; font-weight: bold; vertical-align: top;">Details:</td>
                            <td style="padding: 10px 0; border-bottom: 1px solid #eee;">${details.replace(/\n/g, '<br/>')}</td>
                        </tr>` : ''}
                    </table>

                    <div style="margin-top: 20px;">
                        <p style="font-weight: bold; margin-bottom: 5px;">Message/Comments:</p>
                        <div style="background: #f9f9f9; border-left: 4px solid #007bff; padding: 15px; font-style: italic; color: #555;">
                            ${(message || 'No additional message provided.').replace(/\n/g, '<br/>')}
                        </div>
                    </div>

                    ${fileLinksHtml}
                </div>
                
                <div style="background: #f4f4f4; padding: 15px; border-radius: 0 0 8px 8px; font-size: 0.85rem; color: #666; text-align: center;">
                    <p style="margin: 0;">Generated by <strong>Damascus Translation Platform</strong></p>
                    <p style="margin: 5px 0 0 0;">© ${new Date().getFullYear()} Damascus Translation Services</p>
                </div>
            </div>
        `;

        const resendResponse = await fetch('https://api.resend.com/emails', {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${env.RESEND_API_KEY}`,
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                from: 'Damascus Translation <notifications@damascustranslations.com>',
                to: ['damascustranslation@gmail.com'],
                reply_to: email,
                subject: `${isQuotation ? '⚡ QUOTE' : '✉️ CONTACT'}: ${name}`,
                html: htmlBody,
            }),
        });

        const result = await resendResponse.json() as any;
        return new Response(JSON.stringify(result), {
            status: resendResponse.ok ? 200 : 400,
            headers: { 'Content-Type': 'application/json' }
        });
    } catch (error: any) {
        return new Response(JSON.stringify({ error: error.message }), {
            status: 500,
            headers: { 'Content-Type': 'application/json' }
        });
    }
};
